name = "lfc-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGINS = "https://app.lfc.dev"

# Secrets (set via `wrangler secret put`):
#   JWT_SECRET

[[d1_databases]]
binding = "DB"
database_name = "lfc-db"
database_id = "a15d80ea-de07-4cc3-9d5d-1cf19e29faef"
migrations_dir = "migrations"

[env.production]
routes = [{ pattern = "api.lfc.dev", custom_domain = true }]

[env.production.vars]
CORS_ORIGINS = "https://app.lfc.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "lfc-db"
database_id = "a15d80ea-de07-4cc3-9d5d-1cf19e29faef"
migrations_dir = "migrations"
